### ISSUE TITLE
Make Hosted Zone ID + Route53 Credentials support Docker Secrets with _FILE Suffix

### ISSUE THREAD

**Issue by prononext** [crazy-max/ddns-route53#1003]
### Description

It would be really nice to have the possibility to use Docker Secrets on the following ENVs

- DDNSR53_CREDENTIALS_ACCESSKEYID
- DDNSR53_CREDENTIALS_SECRETACCESSKEY
- DDNSR53_ROUTE53_HOSTEDZONEID

The ENVs should support the _FILE suffix to get it working like this:

- DDNSR53_CREDENTIALS_ACCESSKEYID_FILE
- DDNSR53_CREDENTIALS_SECRETACCESSKEY_FILE
- DDNSR53_ROUTE53_HOSTEDZONEID_FILE

So you can use the docker stack in a more save manner and create the docker secrets before you run the stack in a excrypted manner https://docs.docker.com/engine/reference/commandline/secret_create/

```
version: '3.9'

services:

  ddns-route53:
    image: crazymax/ddns-route53:latest
    secrets:
      - AWS_HOSTED_ZONE_ID_EXAMPLE_COM
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    environment:
      - TZ=Europe/Amsterdam
      - SCHEDULE=* * * * *
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DDNSR53_CREDENTIALS_ACCESSKEYID_FILE=/run/secrets/AWS_ACCESS_KEY_ID
      - DDNSR53_CREDENTIALS_SECRETACCESSKEY_FILE=/run/secrets/AWS_SECRET_ACCESS_KEY
      - DDNSR53_ROUTE53_HOSTEDZONEID_FILE=/run/secrets/AWS_HOSTED_ZONE_ID_EXAMPLE_COM
      - DDNSR53_ROUTE53_RECORDSSET_0_NAME=domain.example.com
      - DDNSR53_ROUTE53_RECORDSSET_0_TYPE=A
      - DDNSR53_ROUTE53_RECORDSSET_0_TTL=60
      
      
secrets:
  # AWS DNS
  AWS_HOSTED_ZONE_ID_EXAMPLE_COM:
    name: AWS_HOSTED_ZONE_ID_EXAMPLE_COM
    external: true
  AWS_ACCESS_KEY_ID:
    name: AWS_ACCESS_KEY_ID
    external: true
  AWS_SECRET_ACCESS_KEY:
    name: AWS_SECRET_ACCESS_KEY
    external: true    
```
