### ISSUE TITLE
General Question: can i use an apex domain with this tool?

### ISSUE THREAD

**Issue by mar005** [crazy-max/ddns-route53#174]
I currently use this with a subdomain and love it but running my blog I wanted to resolve an apex domain to a CNAME which recursively points to the A record that this docker updates with my home IP. However you can’t CNAME apex (root domain names) in AWS. Wondering if I can add just the root address as an A record and this will update it?

**Comment by crazy-max** [comment]
@mar005 Sure you could do this with something like this:

```yaml
credentials:
  accessKeyID: "ABCDEFGHIJKLMNO123456"
  secretAccessKey: "abcdefgh123456IJKLMN+OPQRS7890+ABCDEFGH"

route53:
  hostedZoneID: "ABCEEFG123456789"
  recordsSet:
    - name: "example.com."
      type: "A"
      ttl: 300
    - name: "ddns.example.com."
      type: "A"
      ttl: 300
```
