### ISSUE TITLE
Deployment and execution of docker failing on UDM Pro

### ISSUE THREAD

**Issue by thanneman79** [crazy-max/ddns-route53#281]
### Behaviour
Running on Unifi Dream Machine Pro fails on first startup.

#### Steps to reproduce this issue

1. Followed instructions outlined in https://crazymax.dev/ddns-route53/install/unifi-os/
2. Execute service for first time.

#### Expected behaviour

> Service starts with no errors.

#### Actual behaviour

Startup of service produces the following error.

```
# /mnt/data/on_boot.d/20-ddns-route53.sh
Trying to pull docker.io/crazymax/ddns-route53:latest...
Getting image source signatures
Copying blob b538f80385f9 done
Copying blob a3ca3f385fd2 done
Copying blob f03d88339f6b done
Copying blob 28c7e7792935 done
Copying blob 7dc23cf6ac8b done
Copying config 9985eb89eb done
Writing manifest to image destination
Storing signatures
ERRO[0005] Error adding network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]
ERRO[0005] Error while adding to cni lo network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]
Error: error configuring network namespace for container a16cce8dae48b8bb68e37580b4053d3f2ec7a7b74951bfe9c4706a51384f9c4e: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]
```

### Configuration

* ddns-route53 version : latest
* Platform (windows/linux) : UDM Pro
* System info (type `uname -a`) : Linux FTLGATE 4.1.37-v1.8.0.2888-8f25fa3 #1 SMP Wed Aug 19 13:02:14 MDT 2020 aarch64 GNU/Linux

```yml
credentials:
  accessKeyID: "redacted"
  secretAccessKey: "redacted"

route53:
  hostedZoneID: "redacted"
  recordsSet:
    - name: "redacted.net."
      type: "A"
      ttl: 300
    - name: "redacted.net."
      type: "AAAA"
      ttl: 300
```

### Logs

```
# paste logs here (set log level to debug first)
```
None Produced
