### ISSUE TITLE
Request to https://v4.ident.me returns "connection refused"

### ISSUE THREAD

**Issue by bitbldr** [crazy-max/ddns-route53#330]
### Behaviour
Running using docker image fails to retrieve the IP from https://v4.ident.me.

```
ddns-route53    | Mon, 04 Jan 2021 19:04:29 EST INF Starting ddns-route53 version=2.2.0
ddns-route53    | Mon, 04 Jan 2021 19:04:29 EST INF Configuration loaded from file: /ddns-route53.yml
ddns-route53    | Mon, 04 Jan 2021 19:04:30 EST ERR Cannot retrieve WAN IPv4 address error="request failed: Get \"https://v4.ident.me/\": dial tcp 0.0.0.0:443: connect: connection refused"
ddns-route53    | Mon, 04 Jan 2021 19:04:30 EST INF Cron initialized with schedule 0 */5 * * * *
ddns-route53    | Mon, 04 Jan 2021 19:04:30 EST INF Next run in 29 seconds (2021-01-04 19:05:00 -0500 EST)
```

#### Steps to reproduce this issue

1. Run `docker-compose up` with the following docker-compose file
```
version: "3.5"
services:
  ddns-route53:
    image: crazymax/ddns-route53:latest
    restart: always
    container_name: ddns-route53
    volumes:
      - ./ddns-route53.yml:/ddns-route53.yml:ro
    environment:
      - "TZ=America/New_York"
      - "SCHEDULE=0 */5 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
```

Output returns an error:
```
ddns-route53    | Mon, 04 Jan 2021 19:10:37 EST INF Starting ddns-route53 version=2.2.0
ddns-route53    | Mon, 04 Jan 2021 19:10:37 EST INF Configuration loaded from file: /ddns-route53.yml
ddns-route53    | Mon, 04 Jan 2021 19:10:38 EST ERR Cannot retrieve WAN IPv4 address error="request failed: Get \"https://v4.ident.me/\": dial tcp 0.0.0.0:443: connect: connection refused"
ddns-route53    | Mon, 04 Jan 2021 19:10:38 EST INF Cron initialized with schedule 0 */5 * * * *
ddns-route53    | Mon, 04 Jan 2021 19:10:38 EST INF Next run in 4 minutes (2021-01-04 19:15:00 -0500 EST)
```

#### Expected behaviour

> Should retrieve IP from v4.ident.me and update route 53

#### Actual behaviour

> Fails to retrieve IP from https://v4.ident.me with "connection refused"
### Configuration

* ddns-route53 version : 
* Platform (windows/linux) :
* System info (type `uname -a`) : 

cat ddns-route53.yml 
```yml
credentials:
  accessKeyID: "###########################"
  secretAccessKey: "###########################"

route53:
  hostedZoneID: "###########################"
  recordsSet:
    - name: "#######.#######."
      type: "A"
      ttl: 180
    # - name: "another.example2.com."
    #   type: "A"
    #   ttl: 300
```

### Logs

```
$ docker-compose up
Recreating ddns-route53 ... done
Attaching to ddns-route53
ddns-route53    | Mon, 04 Jan 2021 19:15:55 EST INF Starting ddns-route53 version=2.2.0
ddns-route53    | Mon, 04 Jan 2021 19:15:55 EST INF Configuration loaded from file: /ddns-route53.yml
ddns-route53    | Mon, 04 Jan 2021 19:15:55 EST DBG No DDNSR53_* environment variables defined
ddns-route53    | Mon, 04 Jan 2021 19:15:55 EST DBG {
ddns-route53    |   "credentials": {
ddns-route53    |     "accessKeyID": "###########################",
ddns-route53    |     "secretAccessKey": "###########################"
ddns-route53    |   },
ddns-route53    |   "route53": {
ddns-route53    |     "hostedZoneID": "###########################",
ddns-route53    |     "recordsSet": [
ddns-route53    |       {
ddns-route53    |         "name": "#######.#######.",
ddns-route53    |         "type": "A",
ddns-route53    |         "ttl": 180
ddns-route53    |       }
ddns-route53    |     ]
ddns-route53    |   }
ddns-route53    | }
ddns-route53    | Mon, 04 Jan 2021 19:15:56 EST ERR Cannot retrieve WAN IPv4 address error="request failed: Get \"https://v4.ident.me/\": dial tcp 0.0.0.0:443: connect: connection refused"
ddns-route53    | Mon, 04 Jan 2021 19:15:56 EST INF Cron initialized with schedule 0 */5 * * * *
ddns-route53    | Mon, 04 Jan 2021 19:15:56 EST INF Next run in 4 minutes (2021-01-04 19:20:00 -0500 EST)
```

Really appreciate this useful utility, it would be great if I could figure out what is causing the issue here, or somehow specify a different IP lookup command such as `dig +short myip.opendns.com @resolver1.opendns.com`. Thanks!
