### ISSUE TITLE
Multiarch package? Not working on armv7.

### ISSUE THREAD

**Issue by garyritchie** [crazy-max/ddns-route53#4]
#### Steps to reproduce this issue

1. Pulling to ODROID-HC2 as a NAS running OpenMediaVault
2. `docker-compose up` resulting in "exec format error"

#### Expected behaviour

Container should run. Works from amd64 desktop (Windows10).

#### Actual behaviour

```bash
Creating ddns-route53 ... done
Attaching to ddns-route53
ddns-route53 | standard_init_linux.go:211: exec user process caused "exec format error"
$ uname -a
Linux odroidnas 4.14.133-odroidxu4 #2 SMP PREEMPT Tue Jul 16 19:33:01 CEST 2019 armv7l GNU/Linux
```

### Configuration

* ddns-route53 version :  latest
* Platform (windows/linux) :  Debian GNU/Linux 9.9 (stretch)
* Docker:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:35:21 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:29:21 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```yml
credentials:
  access_key_id: "keyid"
  secret_access_key: "key"

route53:
  hosted_zone_id: "Zone"
  records_set:
    - name: "intranet.example.com."
      type: "A"
      ttl: 300
```
