### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by jaysonsandoval** [crazy-max/ddns-route53#983]
### Description

Is there a way to configure this script for multiple domains and sub-domains?

**Comment by jcgoette** [comment]
Looks doable via [config file](https://crazymax.dev/ddns-route53/config/#configuration-file) or [env variables](https://crazymax.dev/ddns-route53/config/#environment-variables):

```
credentials:
  accessKeyID: "ABCDEFGHIJKLMNO123456"
  secretAccessKey: "abcdefgh123456IJKLMN+OPQRS7890+ABCDEFGH"

route53:
  hostedZoneID: "ABCEEFG123456789"
  recordsSet:
    **- name: "ddns.example.com."**
      type: "A"
      ttl: 300
    **- name: "ddns.example.com."**
      type: "AAAA"
      ttl: 300
    **- name: "another.example2.com."**
      type: "A"
      ttl: 600
```

```
DDNSR53_CREDENTIALS_ACCESSKEYID=ABCDEFGHIJKLMNO123456
DDNSR53_CREDENTIALS_SECRETACCESSKEY=abcdefgh123456IJKLMN+OPQRS7890+ABCDEFGH

DDNSR53_ROUTE53_HOSTEDZONEID=ABCEEFG123456789
**DDNSR53_ROUTE53_RECORDSSET_0_NAME=ddns.example.com.**
DDNSR53_ROUTE53_RECORDSSET_0_TYPE=A
DDNSR53_ROUTE53_RECORDSSET_0_TTL=300
**DDNSR53_ROUTE53_RECORDSSET_1_NAME=ddns.example.com.**
DDNSR53_ROUTE53_RECORDSSET_1_TYPE=AAAA
DDNSR53_ROUTE53_RECORDSSET_1_TTL=300
**DDNSR53_ROUTE53_RECORDSSET_2_NAME=another.example2.com.**
DDNSR53_ROUTE53_RECORDSSET_2_TYPE=A
DDNSR53_ROUTE53_RECORDSSET_2_TTL=600
```
